// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlzCdA1M9LVMNzwYRxAUiy-Ht5BQh6L88',
    appId: '1:1040126928583:web:c1b80f8ab523ec55e500e2',
    messagingSenderId: '1040126928583',
    projectId: 'flutter-chatting-app-f8259',
    authDomain: 'flutter-chatting-app-f8259.firebaseapp.com',
    storageBucket: 'flutter-chatting-app-f8259.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD4F-yJyHuLnGmi4cImDQYZ0_GwzXzbQk',
    appId: '1:1040126928583:android:2d1a1b495889c8bbe500e2',
    messagingSenderId: '1040126928583',
    projectId: 'flutter-chatting-app-f8259',
    storageBucket: 'flutter-chatting-app-f8259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8M66nBghGGodmOFaVWDWA5c603lhABOg',
    appId: '1:1040126928583:ios:891dea3c575d5dade500e2',
    messagingSenderId: '1040126928583',
    projectId: 'flutter-chatting-app-f8259',
    storageBucket: 'flutter-chatting-app-f8259.firebasestorage.app',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8M66nBghGGodmOFaVWDWA5c603lhABOg',
    appId: '1:1040126928583:ios:891dea3c575d5dade500e2',
    messagingSenderId: '1040126928583',
    projectId: 'flutter-chatting-app-f8259',
    storageBucket: 'flutter-chatting-app-f8259.firebasestorage.app',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlzCdA1M9LVMNzwYRxAUiy-Ht5BQh6L88',
    appId: '1:1040126928583:web:e8ce54cad2ff817ce500e2',
    messagingSenderId: '1040126928583',
    projectId: 'flutter-chatting-app-f8259',
    authDomain: 'flutter-chatting-app-f8259.firebaseapp.com',
    storageBucket: 'flutter-chatting-app-f8259.firebasestorage.app',
  );
}
